### ISSUE TITLE
kvmtool compiled with GCC 6 will fail

### ISSUE THREAD

**Issue by doegox** [cappsule/nofear#6]
To reproduce the bug:

Have GCC >= 6.2 by default (mine was gcc (Debian 6.2.1-5) 6.2.1 20161124)
```bash
./build.sh kvmtool
sudo ./install.sh
nofear -d default
nofear
# Fatal: Fail to setup /home/foo/.lkvm/default/virt/pre_init
```
When compiling with v6 there is zero extra warning compared to v5.

**Comment by cappsule** [comment]
Thanks for the bug report, @doegox! I sent an email to the kvmtool mailing list (https://www.spinics.net/lists/kvm/msg143014.html) since the bug seems to be in kvmtool.

**Comment by cappsule** [comment]
The commit 3a48ecd8c9d42c4fa684d2bbe185f8f5a3725fdd fixes this issue (and the patch has also been sent upstream).
